import { useTranslate } from '~/i18n';
import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { useRouter } from 'next/router';
// import classNames from 'classnames';
import Axios from '~/utils/axios';
import ButtonBtn from '../shared/buttons/button-btn';
// import { TeamType } from '~/interfaces/team';
import { WinnerType } from '~/interfaces/winner';
import Confetti from '../draw/confetti';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const WinnerSections = () => {
   const router = useRouter();

   const { lang, translate } = useTranslate();
   const [loading, setLoading] = useState(false);
   const [winner, setWinner] = useState<WinnerType>();
   const start = async () => {
      if (loading) {
         return;
      }
      setLoading(true);
      try {
         const response = await Axios.get(`get-winner/${router.query?.slug}?lang=${lang}`);
         setWinner(response.data.data);
         // if (response.data.status === 'failed') {
         //    toast.error('Please wait', {
         //       duration: 3000,
         //    });
         // } else {
         //    toast.success('Game Started', {
         //       duration: 3000,
         //    });
         //    router.replace(
         //       `/contests/${router.query?.slug}/team/${router.query?.team_id}/questions`
         //    );
         // }
      } catch (error: any) {
         toast.error(translate({ id: 'res:500' }), {
            duration: 3000,
         });
      }
      setLoading(false);
   };
   return (
      <React.Fragment>
         <div className="container">
            <div className="row">
               <div className="col-12 mt-10">
                  <div className="mb-5 text-center">
                     <h1 className="col-12 relative font-black text-white">
                        <div className="text-6xl">{'Trivia Game'}</div>
                        <div className="text-4xl">{'Cybersecurity Annual Gathering 2023'}</div>
                     </h1>
                  </div>
               </div>
               {winner ? (
                  <React.Fragment>
                     <Confetti />
                     <div className="text-center">
                        <span className="mt-5 inline-block rounded-full bg-white px-4 text-6xl text-primary">
                           {winner.name}
                        </span>
                        <div className="mt-4 text-white">Score: {winner.score}</div>
                        <div className="text-white">Completed at: {winner.duration} seconds</div>
                     </div>
                  </React.Fragment>
               ) : (
                  <div className="mx-auto lg:col-3">
                     <div className="mt-5">
                        <ButtonBtn
                           id=""
                           callBack={() => {
                              start();
                           }}
                           noIcon
                           loading={loading}
                           text={'SHOW WINNER'}
                        />
                     </div>
                  </div>
               )}
            </div>
         </div>
      </React.Fragment>
   );
};

export default WinnerSections;
