// import Image from '~/components/shared/image';
// import Image from '~/components/shared/image';
// import Image from '~/components/shared/image';
// import { Translate } from '~/i18n';
// import { publicUrl } from '~/utils/publicUrl';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const Section3 = () => {
   // const { lang } = useTranslate();
   // const stores = [
   //    {
   //       href: '',
   //       src: `/images/app/${lang}/app_store.png`,
   //       label: 'app store',
   //    },
   //    {
   //       href: '',
   //       src: `/images/app/${lang}/google_play.png`,
   //       label: 'google play',
   //    },
   // ];
   return (
      <section>
         <div className="relative text-center">
            <div className="absolute bottom-0  hidden w-full overflow-hidden    md:block">
               <div className="relative   -mr-16 h-[300px] bg-body-bg bg-contain bg-center bg-no-repeat"></div>
            </div>
            <div className="container md:px-12">
               <div className="row pt-16 pb-4">
                  {/* <div className="col-12 self-center">
                     <small className="text-white">
                        <Translate id="common:app_copyright" /> © {new Date().getFullYear()}
                     </small>
                  </div> */}
               </div>
            </div>
         </div>
      </section>
   );
};

export default Section3;
