import { NextLink, Translate, useTranslate } from '~/i18n';
import React, { useEffect, useState } from 'react';
// import { useForm } from 'react-hook-form';
// import CustomInput from '../shared/forms/custom-input';
// import SubmitBtn from '../shared/buttons/submit-btn';
// import toast from 'react-hot-toast';
import { useRouter } from 'next/router';
// import classNames from 'classnames';
// import Cookies from 'js-cookie';
import Axios from '~/utils/axios';
// import { OptionType } from '~/interfaces/option';
import { ScoreType } from '~/interfaces/score';
// import ButtonBtn from '../shared/buttons/button-btn';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const ScoreSections = () => {
   const { lang } = useTranslate();
   const [loading, setLoading] = useState(false);
   const [score, setScore] = useState<ScoreType>();
   // console.log(question, 'question');

   const router = useRouter();
   useEffect(() => {
      async function getUserData() {
         setLoading(true);
         try {
            const response = await Axios.get(
               `/get-score/${router.query?.slug}/${router.query?.team_id}?lang=${lang}`
            );
            // console.log(response);
            setScore(response.data.data);
         } catch (error: any) {
            // setHasError(true);
         }
         setLoading(false);
      }

      if (router) {
         getUserData();
      }
   }, [lang, router]);

   return (
      <React.Fragment>
         {!loading && (
            <section>
               <div className="container py-10">
                  <div className="row">
                     <div className="lg:col-6 lg:offset-3">
                        <div className="">
                           <div className="p-1 sm:p-1">
                              <div className="text-center">
                                 <div className="relative z-10">
                                    <h1 className=" text-2xl font-bold text-white">
                                       <Translate id="web:thank_you" />
                                    </h1>

                                    <div className="mt-1 text-lg font-bold text-white">
                                       <Translate id="web:your_score" />
                                    </div>
                                    <div className="mx-auto mt-2 flex h-[100px] w-[100px] items-center justify-center rounded-full bg-white">
                                       <div className="text-3xl font-bold text-primary">
                                          {score?.score}/{score?.total_question}
                                       </div>
                                    </div>
                                    <div className="mt-5 text-center">
                                       <NextLink
                                          href={''}
                                          className={
                                             'text-md bg-secondary hover:bg-secondary-600 active:bg-secondary inline-block rounded-full border border-white px-4 py-2 text-center font-medium leading-5 text-white transition-colors duration-150  focus:outline-none'
                                          }>
                                          <Translate id="web:back_to_homepage" />
                                       </NextLink>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </section>
         )}
      </React.Fragment>
   );
};

export default ScoreSections;
