import { useTranslate } from '~/i18n';
import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { useRouter } from 'next/router';
// import classNames from 'classnames';
import Axios from '~/utils/axios';
import ButtonBtn from '../shared/buttons/button-btn';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const StartSections = () => {
   const router = useRouter();

   const { lang, translate } = useTranslate();
   const [loading, setLoading] = useState(false);
   const start = async () => {
      if (loading) {
         return;
      }
      setLoading(true);
      try {
         const response = await Axios.get(
            `contests-status/${router.query?.slug}/${router.query?.team_id}?lang=${lang}`
         );
         if (response.data.status === 'failed') {
            toast.error('Please wait', {
               duration: 3000,
            });
         } else {
            toast.success('Game Started', {
               duration: 3000,
            });
            router.replace(
               `/contests/${router.query?.slug}/team/${router.query?.team_id}/questions`
            );
         }
      } catch (error: any) {
         toast.error(translate({ id: 'res:500' }), {
            duration: 3000,
         });
      }
      setLoading(false);
   };
   return (
      <React.Fragment>
         <div className="container">
            <div className="row">
               <div className="col-12 mt-10">
                  <div className="mb-5 text-center">
                     <h1 className="col-12 relative   font-black text-white">
                        <div className="text-4xl">{'Trivia Game'}</div>
                        <div className="text-2xl">{'Cybersecurity Annual Gathering 2023'}</div>
                     </h1>
                  </div>
               </div>
               <div className="mx-auto lg:col-3">
                  <div className="mt-5">
                     <ButtonBtn
                        id=""
                        callBack={() => {
                           start();
                        }}
                        noIcon
                        loading={loading}
                        text={'START'}
                     />
                  </div>
               </div>
            </div>
         </div>
      </React.Fragment>
   );
};

export default StartSections;
