import React from 'react';
import { useFormContext } from 'react-hook-form';
import { useTranslate } from '~/i18n';
import cookie from 'js-cookie';
import { GuestType } from '~/interfaces/guest';
import CustomRadioInput from '~/components/shared/forms/custom-radio-input';
import { QuestionType } from '~/interfaces/question';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type Question7Props = {
   onNextClick: () => any;
   step?: string | undefined;
   showStepSummary?: boolean;
   nextStep?: string;
   question: QuestionType;
};

const Question7 = ({ onNextClick, step, nextStep, question }: Question7Props) => {
   const { translate } = useTranslate();
   const {
      register,
      // handleSubmit,

      formState: { errors },
   } = useFormContext<GuestType>();

   const submitForm = async (value: string) => {
      try {
         const userData = cookie.get('user_data') && JSON.parse(cookie.get('user_data') as any);
         const updatedUserObj = {
            ...userData,
            question_7: value,
            step: nextStep,
         };

         cookie.set('user_data', JSON.stringify(updatedUserObj));
         onNextClick();
      } catch (error: any) {
         console.log(error, 'error');
      }
   };

   return (
      <React.Fragment>
         {step === 'question_7' ? (
            <div>
               <div className="p-1 sm:p-1">
                  <div className="pt-1">
                     <form noValidate className="relative" autoComplete="off">
                        {/* question_7 */}
                        <CustomRadioInput
                           label={translate({ id: 'web:question_7' })}
                           subLabel={question.sub_label}
                           // isRequired
                           isInline={false}
                           callBack={val => submitForm(val)}
                           // return  { value: 'male', label: translate({ id: 'web:male' }) },
                           options={question.options.map(item => {
                              return { label: item, value: item };
                           })}
                           id="question_7"
                           error={errors.question_7?.message}
                           {...register('question_7', {
                              required: translate({ id: 'validation:required' }),
                           })}
                        />
                     </form>
                  </div>
               </div>
            </div>
         ) : (
            ''
         )}
      </React.Fragment>
   );
};

export default Question7;
