/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const Test = () => {
   return (
      <div>
         <div className="row text-4xl">
            <div className="col-6">
               <div className="font-normal text-white">fonts test</div>
               <div className="font-thin text-white">fonts test</div>
               <div className="font-extralight text-white">fonts test</div>
               <div className="font-normal text-white">fonts test</div>
               <div className="font-medium text-white">fonts test</div>
               <div className="font-semibold text-white">fonts test</div>
               <div className="font-bold text-white">fonts test</div>
               <div className="font-extrabold text-white">fonts test</div>
               <div className="font-black text-white">fonts test</div>
            </div>
            <div className="col-6">
               <div className="font-normal text-white">تجربة الخطوط</div>
               <div className="font-thin text-white">تجربة الخطوط</div>
               <div className="font-extralight text-white">تجربة الخطوط</div>
               <div className="font-normal text-white">تجربة الخطوط</div>
               <div className="font-medium text-white">تجربة الخطوط</div>
               <div className="font-semibold text-white">تجربة الخطوط</div>
               <div className="font-bold text-white">تجربة الخطوط</div>
               <div className="font-extrabold text-white">تجربة الخطوط</div>
               <div className="font-black text-white">تجربة الخطوط</div>
            </div>
         </div>
      </div>
   );
};

export default Test;
