// import classNames from 'classnames';

import { CalendarIcon } from '@heroicons/react/24/outline';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

// type CalendarIconAppendProps = {
//    id: string;
// };

const CalendarIconAppend = () => {
   return (
      <span className="block border-primary px-2 text-primary ltr:border-l rtl:border-r">
         <CalendarIcon className="h-4 w-4" />
      </span>
   );
};

export default CalendarIconAppend;
