import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type LabelProps = {
   label?: React.ReactNode | string;
   isRequired?: boolean;
   id?: string;
};

const Label = ({ label, isRequired }: LabelProps) => {
   return (
      <label
         // htmlFor={id}
         className={classNames(
            'block text-center font-bold text-white md:text-lg',
            isRequired && 'required-label'
         )}>
         {label}
      </label>
   );
};

export default Label;
