import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type LabelProps = {
   label?: React.ReactNode | string;
   isRequired?: boolean;
   id?: string;
};

const SubLabel = ({ label, isRequired }: LabelProps) => {
   return (
      <div
         // htmlFor={id}
         className={classNames(
            'inline-flex justify-center rounded-[30px] bg-white px-4 py-2 text-center font-bold text-primary md:text-lg',
            isRequired && 'required-label'
         )}>
         {label}
      </div>
   );
};

export default SubLabel;
