import React, { useEffect, useState } from 'react';
import Cookies from 'js-cookie';
import { NextLink, useTranslate } from '~/i18n';
// import { GuestType } from '~/interfaces/guest';
import { ContestType } from '~/interfaces/contest';
import Axios from '~/utils/axios';
// import { Person } from 'next-seo/lib/types';
// import { useRouter } from 'next/router';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const HomePageSections = () => {
   Cookies.remove('user_data');
   // const router = useRouter();
   const [loading, setLoading] = useState(true);
   const { lang } = useTranslate();
   const [contests, setContests] = useState<ContestType[]>([]);
   // const router = useRouter();
   useEffect(() => {
      async function getUserData() {
         setLoading(true);
         try {
            const response = await Axios.get(`/contests-select?lang=${lang}`);
            // console.log(response);

            setContests(response.data.data);
         } catch (error: any) {
            // setHasError(true);
         }
         setLoading(false);
      }

      getUserData();
   }, [lang]);
   return (
      <section>
         <div className="container">
            <div className=" text-center text-white">
               <div>
                  <h1 className="col-12 relative   font-black text-white">
                     <div className="text-4xl">{'Travis Game'}</div>
                     <div className="text-2xl">{'Cybersecurity Annual Gathering 2023'}</div>
                  </h1>
                  <div className="mt-10">
                     {loading ? (
                        <div>Loading ...</div>
                     ) : (
                        <React.Fragment>
                           {contests.map((item, index) => (
                              <div className="mb-2" key={index}>
                                 <NextLink
                                    href={`/contests/${item.slug}/add-team`}
                                    className={
                                       'text-md inline-block rounded-full border border-white bg-primary  px-10 py-3 text-center font-medium leading-5 text-white transition-colors duration-150 hover:bg-primary-600 focus:outline-none  active:bg-primary'
                                    }>
                                    {item.name}
                                 </NextLink>
                              </div>
                           ))}
                        </React.Fragment>
                     )}
                  </div>
               </div>
            </div>
         </div>
      </section>
   );
};

export default HomePageSections;
