// import React from 'react';

import { NextLink, Translate } from '~/i18n';
import RegionsTypeSelect from '~/data/status-types-select';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const Regions = () => {
   return (
      <div className="container">
         <div className="row">
            <div className="col-12 text-center ">
               <h1 className="text-5xl uppercase text-white">
                  <Translate id="web:draw" />
               </h1>
            </div>
            {RegionsTypeSelect.map((item, index) => (
               <div className="col-12" key={index}>
                  <div className="mt-5 text-center">
                     <NextLink
                        href={`/draw/${item.value}`}
                        className={
                           'text-md inline-block rounded-full border border-white bg-secondary px-4 py-2 text-center font-medium leading-5 text-white transition-colors duration-150 hover:bg-secondary-600 focus:outline-none  active:bg-secondary'
                        }>
                        {item.label}
                     </NextLink>
                  </div>
               </div>
            ))}
         </div>
      </div>
   );
};

export default Regions;
